modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Rain%20Be%20Gone%20Ritual"
logoFile="icon.png"

[[mods]]
modId="rainbegoneritual"
version="3.1"
displayName="Rain Be Gone Ritual"
displayURL="https://curseforge.com/minecraft/mc-mods/rain-be-gone-ritual"
authors="Rick South"
description='''Adds the ability to stop the rain with a multi-block structure ritual.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.rainbegoneritual]]
    modId="collective"
    mandatory=true
    versionRange="[7.12,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.rainbegoneritual]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.3]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "rainbegoneritual_neoforge.mixins.json"